{
  "hash": "8fb13001c96b36e586753eec5963e685",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"1.1 Feature Extraction\"\nsubtitle: \"ORB-SLAM3 — Visuelle Merkmale erkennen und beschreiben\"\nauthor: \"Nediljko Andrijanic\"\ndate: today\nlang: de\nformat:\n  html:\n    theme: darkly\n    toc: true\n    toc-depth: 2\n    toc-title: \"Inhalt\"\n    number-sections: false\n    fig-align: center\n    highlight-style: github-dark\n    embed-resources: true\nexecute:\n  echo: false\n  eval: true\n  warning: false\n  message: false\n---\n\n\n## Schritt 1: Graustufen\n\n::: {style=\"background:#1a2a1a; border-left:4px solid #4caf50; padding:6px 12px; margin-bottom:8px; font-size:0.85em;\"}\n**Eingang:** RGB-Kamerabild &nbsp;→&nbsp; **Ausgang → Schritt 2:** Graustufenbild (1 Kanal, Helligkeit 0–255)\n:::\n\n**Warum nur Helligkeit, nicht Farbe?**\n\n- **Farbe ändert sich mit Beleuchtung:** Ein rotes Objekt kann dunkelrot oder hellrot sein — die Form ist aber gleich\n- **Kanten sind Helligkeitsunterschiede:** Ein dunkler Bereich neben einem hellen Bereich erzeugt eine Kante — egal welche Farben\n- **Computer Vision braucht Struktur, nicht Farbe:** Features sind geometrische Muster (Ecken, Kanten, Gradienten) — diese basieren auf Helligkeit\n- **Rechenzeit sparen:** 3 Kanäle (RGB) → 1 Kanal (Gray) = 3× schneller\n\n**Die Formel gewichtet Grün am stärksten, weil das menschliche Auge dafür am empfindlichsten ist:**\n\n$$I_{grau} = 0.299 \\cdot R + 0.587 \\cdot G + 0.114 \\cdot B$$\n\n::: {#b2b70aae .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-3-output-1.png){width=1288 height=468 fig-align='center'}\n:::\n:::\n\n\n## Schritt 2: Gauss-Filter\n\n::: {style=\"background:#1a2a1a; border-left:4px solid #4caf50; padding:6px 12px; margin-bottom:8px; font-size:0.85em;\"}\n**Eingang:** Graustufenbild &nbsp;→&nbsp; **Ausgang → Schritt 3:** geglättetes Bild (Rauschen reduziert)\n:::\n\n### 2.1 Was macht Filter?\n\n**Problem:** Kamerasensoren erzeugen Rauschen — zufällige Helligkeits-Schwankungen die keine echten Ecken sind.\n\n**Lösung:** Jeder Pixel bekommt einen neuen Wert = **gewichteter Durchschnitt** seiner Nachbarn.\n- Nachbar-Pixel in der **Nähe** zählen mehr\n- Nachbar-Pixel weit weg zählen weniger\n- Rauschen wird geglättet\n- Echte Kanten bleiben erhalten\n\n\n### 2.2 Wie berechnet man?\n\nDer Filter verwendet eine **Gauss-Kurve** als Gewichtung:\n\n$$G(x,y) = \\frac{1}{2\\pi\\sigma^2} e^{-\\frac{x^2+y^2}{2\\sigma^2}}$$\n\n**Was sind x und y?** — Die **Koordinaten relativ zur Mitte** des 5×5 Kernels:\n\n```\n        x →  -2   -1    0   +1   +2\n             ┌────┬────┬────┬────┬────┐\n        y -2 │    │    │    │    │    │\n             ├────┼────┼────┼────┼────┤\n        y -1 │    │    │    │    │    │\n             ├────┼────┼────┼────┼────┤\n        y  0 │    │    │ M  │    │    │  ← Center (x=0, y=0)\n             ├────┼────┼────┼────┼────┤\n        y +1 │    │    │    │    │    │\n             ├────┼────┼────┼────┼────┤\n        y +2 │    │    │    │    │    │\n             └────┴────┴────┴────┴────┘\n```\n\n**Beispiele — je weiter weg, desto kleiner das Gewicht:**\n\n| Position | x | y | Entfernung | Gewicht |\n|----------|---|---|------------|---------|\n| **Mitte** | 0 | 0 | 0 | **0.195** (19.5%) |\n| Rechts | 1 | 0 | 1 | 0.071 (7.1%) |\n| Diagonal | 1 | 1 | √2 ≈ 1.4 | 0.025 (2.5%) |\n| **Eck** | 2 | 2 | √8 ≈ 2.8 | **0.004** (0.4%) |\n\nDie Gewichte sind so normalisiert, dass sie sich zu **1.0** addieren.\n\n### 2.3 Was ist das Ergebnis?\n\n**Vorher und Nachher — das ganze Bild:**\n\n::: {#0e6041fa .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-5-output-1.png){width=935 height=483 fig-align='center'}\n:::\n:::\n\n\nAlle Pixel haben sich verändert — der größte Ausreißer (250 in der Mitte) wird besonders stark nach unten gezogen, weil alle Nachbarn (~20) zusammen viel mehr Gewicht haben.\n\n**Detaillierte Berechnung — nur für den Zentral-Pixel mit Wert 250:**\n\n::: {#f0563064 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-6-output-1.png){width=1332 height=553 fig-align='center'}\n:::\n:::\n\n\n---\n\n**Wichtig:** Der Filter liest **immer vom Original-Bild** (nicht von bereits geänderten Pixeln) — so bekommt jeder Pixel eine faire, konsistente Behandlung ohne Kaskadeneffekte.\n\n:::\n\n\n\n## Schritt 3: FAST Detektor — Theorie\n\n::: {style=\"background:#1a2a1a; border-left:4px solid #4caf50; padding:6px 12px; margin-bottom:8px; font-size:0.85em;\"}\n**Eingang:** geglättetes Bild &nbsp;→&nbsp; **Ausgang → Schritt 4:** viele Keypoints (Ecken) mit Position (x, y)\n:::\n\n**Ziel:** Finde Ecken im Bild. Eine Ecke ist ein Punkt, wo sich Helligkeit abrupt in zwei Richtungen ändert.\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Algorithmus — für jeden Pixel p:**\n\n1. Zeichne einen Kreis mit **16 Nachbarn** (Radius 3)\n2. Prüfe ob ≥ **9 zusammenhängende** Pixel entweder:\n   - **Heller** sind: $I_x > I_p + t$\n   - **Dunkler** sind: $I_x < I_p - t$\n3. Falls ja → **Ecke erkannt**\n\n$t$ = Schwellenwert\n\n**Warum 9?** Mindestens die Hälfte+1 des Kreises (16/2 + 1 = 9) muss konsistent sein.\n:::\n::: {.column width=\"45%\"}\n```\n     ×  ×  ×\n   ×  1  2  3  ×\n  × 16        4 ×\n  × 15    p   5 ×    ← Zentrum p\n  × 14        6 ×\n   × 13  8  7  ×\n     × 12 11 10 9 ×\n\nWenn z.B. Pixel 1–10 alle\ndunkler als p−t sind:\n→ 10 zusammenhängende\n→ ECKE!\n```\n:::\n:::\n\n\n\n## Schritt 3: FAST Detektor — Pixel-Grid Beispiel\n\n::: {#b67831a2 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-7-output-1.png){width=1257 height=564 fig-align='center'}\n:::\n:::\n\n\n## Schritt 4: Bildpyramide — Theorie\n\n> **Wir kennen jetzt FAST.** Aber FAST findet ein Objekt nur in **einer** Größe — ein zu großes/zu nahes Objekt hat im r=3 Kreis eine zu sanfte Kante. Die Bildpyramide lässt **denselben FAST-Detektor auf mehreren verkleinerten Versionen** des Bildes laufen, sodass auch große Objekte zur Ecke werden.\n\n::: {style=\"background:#1a2a1a; border-left:4px solid #4caf50; padding:6px 12px; margin-bottom:8px; font-size:0.85em;\"}\n**Eingang:** geglättetes Bild + FAST &nbsp;→&nbsp; **Ausgang → Schritt 6:** FAST auf 8 Stufen → skalierungsinvariante Keypoints\n:::\n\n**Problem:** Dasselbe Feature sieht je nach Entfernung anders groß aus.\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Beispiel:**\n- Eine Straßenlaterne **2m** entfernt → groß im Bild\n- Dieselbe Laterne **10m** entfernt → kleiner im Bild\n\n→ ORB ohne Pyramide würde **dieselbe Laterne nicht wiedererkennen**.\n\n**Lösung — Bildpyramide:**\n\nVerarbeite das Bild in **8 Größenstufen** (Skalierungsfaktor 1.2):\n\n| Stufe | Faktor | Bildgröße (Bsp.) |\n|:---:|:---:|:---:|\n| 0 | 1.0× | 800×400 |\n| 1 | 0.83× | 667×333 |\n| 3 | 0.58× | 463×231 |\n| 7 | 0.28× | 223×111 |\n\nFeatures auf Stufe 3 entsprechen Objekten die **1.73× kleiner** erscheinen.\n:::\n::: {.column width=\"45%\"}\n**Warum funktioniert das?**\n\nEin Feature das auf Stufe 0 zu groß erscheint, wird auf Stufe 2 oder 3 erkannt — dort sieht es \"normal groß\" aus.\n\n```\nStufe 0: 800×400  ─── FAST ──→ Features\n  ↓ ÷1.2\nStufe 1: 667×333  ─── FAST ──→ Features\n  ↓ ÷1.2\nStufe 2: 556×278  ─── FAST ──→ Features\n  ...\nStufe 7: 223×111  ─── FAST ──→ Features\n```\n\nAlle Features → auf Originalmaßstab zurückgerechnet.\n:::\n:::\n\n**Wichtig — Rückrechnung auf echte Koordinaten:**\n\nEin Feature das auf Stufe $k$ bei Position $(x_k, y_k)$ gefunden wird, entspricht im **Originalbild** der Position:\n\n$$x_\\text{original} = x_k \\times 1.2^k \\qquad y_\\text{original} = y_k \\times 1.2^k$$\n\nBeispiel: Feature auf Stufe 3 bei $(100, 50)$ → im Original bei $(100 \\times 1.73,\\ 50 \\times 1.73) = (173,\\ 87)$\n\nAlle Features aus allen 8 Stufen werden so ins Original umgerechnet und dann gemeinsam weiterverarbeitet.\n\n\n\n## Schritt 4: Bildpyramide — Beispiel\n\nStatt nur Punkte zu zeigen, demonstrieren wir die Kernidee **konkret an einer einzigen\nStelle** im Bild: eine Position die im Originalbild **keine** Ecke ist, aber auf einer\nkleineren Pyramidenstufe **zur Ecke wird** — und wie ihre Koordinaten zurückgerechnet werden.\n\n\n**Schritt 1–2: Diese Stelle ist auf dem Original keine Ecke — auf der kleineren Stufe schon.**\nDie gefundene Position wird über $x_\\text{orig} = x_k \\times 1.2^k$ zurück ins Originalbild übersetzt.\n\n::: {#8dc2c651 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-9-output-1.png){width=1156 height=691 fig-align='center'}\n:::\n:::\n\n\n**Warum wird die Stelle erst auf der kleineren Stufe zur Ecke?**\nDer FAST-Kreis hat **immer** Radius 3. Auf dem Original ist der Helligkeits-Übergang über\nviele Pixel **verschmiert** — im r=3 Kreis liegen nur wenige dunklere Pixel am Stück.\nBeim Verkleinern werden mehrere alte Pixel zu einem gemittelt, der Übergang wird **steiler**,\nund im selben Kreis liegen jetzt ≥ 9 zusammenhängende dunklere Pixel → **Ecke**.\n\n::: {#5aea9d4b .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-10-output-1.png){width=867 height=874 fig-align='center'}\n:::\n:::\n\n\n**Wie funktioniert die Pyramide?**\n\n- **Stufe 0:** Original-Größe (z.B. 800×400 px)\n- **Stufe 1:** 1.2× verkleinert → 667×333 px\n- **Stufe 2:** 1.2× verkleinert → 556×278 px\n- ...\n- **Stufe 7:** Nach 7 Verkleinerungen → nur noch 223×111 px\n\nJede Stufe ist **exakt 1.2× kleiner** als die vorherige. Dadurch findet FAST **unterschiedliche Objekt-Größen** auf unterschiedlichen Stufen!\n\n**Ergebnis:** Features werden **skalierungsinvariant** — ORB-SLAM3 erkennt dasselbe Objekt in 2m und 10m Entfernung.\n\n### Sub-Pixel Genauigkeit durch die Pyramide\n\nBesonders wichtig: Die Pyramide ermöglicht auch **sehr kleine Features** (weit entfernte Objekte) mit hoher Präzision zu lokalisieren.\n\nWenn FAST ein Feature auf Stufe $k$ findet, wird seine Position auf das **Originalmaßstab zurückgerechnet**:\n\n$$\\text{Position}_\\text{original} = \\text{Position}_\\text{Stufe k} \\times 1.2^k$$\n\nDas bedeutet: 1 Schritt in Stufe $k$ = $1.2^k$ Pixel im Original. Die **effektive Auflösung** ist also:\n\n| Stufe k | Skalierungsfaktor | 1 Pixel entspricht im Original | Genauigkeit |\n|:---:|:---:|:---:|:---:|\n| 0 | 1.0× | 1.00 px | ±1.0 px |\n| 3 | 1.73× | 1.73 px | **±0.58 px** |\n| 5 | 2.49× | 2.49 px | **±0.40 px** |\n| 7 | 3.58× | 3.58 px | **±0.28 px ≈ 0.3 px** |\n\n**Konsequenz:** Ein Feature das auf Stufe 7 bei Position (100, 50) erkannt wird, entspricht im Originalbild **Position (358, 179)** — mit einer Genauigkeit von ~0.28 Pixel. Features aus höheren Stufen haben damit **sub-pixel Präzision** im Originalmaßstab.\n\n**Fazit:** Die Bildpyramide ist nicht nur für Skalierungsinvarianz — sie gibt ORB-SLAM3 auch **sub-pixel Präzision (~0.3 px)** bei der Feature-Lokalisierung auf höheren Stufen.\n:::\n\n\n\n## Schritt 6: Quadtree-Verteilung\n\n::: {style=\"background:#1a2a1a; border-left:4px solid #4caf50; padding:6px 12px; margin-bottom:8px; font-size:0.85em;\"}\n**Eingang:** viele Keypoints (geclustert an Kanten) &nbsp;→&nbsp; **Ausgang → Schritt 7:** gleichmäßig verteilte Keypoints\n:::\n\n**Theorie:** FAST liefert sehr viele Features — aber sie clustern sich alle an denselben Kanten.\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Problem ohne Quadtree:**\n\n- 90% der Features an einer Kante\n- Andere Bildbereiche = **leer**\n- Wenn Kamera dreht → **alle Features verschwinden**!\n\n**Lösung — Quadtree:**\n\n1. Teile Bild in **4 Quadranten**\n2. Jeder Quadrant zu voll → **nochmals teilen**\n3. Wiederholen bis jede Zelle genug Features hat\n4. Pro Zelle → **nur der stärkste** Keypoint bleibt\n\n**Ergebnis:** Features gleichmäßig über das Bild verteilt.\n:::\n::: {.column width=\"50%\"}\n**Visualisierung:**\n\n```\nBild [800×400]\n┌──────────┬──────────┐\n│  Q1      │  Q2      │  pro Quadrant:\n│  125 kps │  125 kps │  max. 125 Features\n├──────────┼──────────┤  → falls mehr:\n│  Q3      │  Q4      │     nochmals teilen\n│  125 kps │  125 kps │\n└──────────┴──────────┘\n\n→ 500 Features total,\n  gleichmäßig verteilt\n```\n:::\n:::\n\n::: {#00c60d43 .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-11-output-1.png){width=1332 height=379 fig-align='center'}\n:::\n:::\n\n\n## Schritt 7: Harris Corner Score\n\n::: {style=\"background:#1a2a1a; border-left:4px solid #4caf50; padding:6px 12px; margin-bottom:8px; font-size:0.85em;\"}\n**Eingang:** verteilte Keypoints (mehrere pro Zelle) &nbsp;→&nbsp; **Ausgang (1.1 fertig):** Top-N stabilste Keypoints mit Position (x,y)\n:::\n\n**Theorie:** Quadtree liefert pro Zelle mehrere Kandidaten — welcher ist der Beste?\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Harris-Response:**\n\n$$R = \\det(M) - k \\cdot \\text{trace}(M)^2, \\quad k \\approx 0.04$$\n\n$$M = \\begin{pmatrix} \\sum I_x^2 & \\sum I_x I_y \\\\ \\sum I_x I_y & \\sum I_y^2 \\end{pmatrix}$$\n\n**Interpretation:**\n- $R \\gg 0$ → **starke Ecke** (beide Richtungen haben Kante)\n- $R < 0$ → Kante (nur eine Richtung)\n- $R \\approx 0$ → flache Region (keine Kante)\n\nPro Quadtree-Zelle → behalte den Keypoint mit dem **höchsten R**.\n:::\n::: {.column width=\"45%\"}\n**Warum nicht einfach den FAST-Score nehmen?**\n\nFAST misst nur ob ein Pixel eine Ecke ist (ja/nein).\nHarris misst **wie stark** die Ecke ist.\n\n→ Harris findet **geometrisch stabilere** Ecken die über viele Frames hinweg wiedererkannt werden.\n:::\n:::\n\n::: {#18923bfe .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![](11_files/figure-html/cell-12-output-1.png){width=1332 height=379 fig-align='center'}\n:::\n:::\n\n\n",
    "supporting": [
      "11_files"
    ],
    "filters": [],
    "includes": {}
  }
}